{% set name = "pandaSDMX" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad33ff7990e06c3b32ac1f71caee824a67ed36abac8edc12d04d986b8e0a1295

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7, <3.9
    - flit >=2.3
    - pip
  run:
    - python >=3.7, <3.9
    - lxml >=3.6
    - pandas >=0.24
    - pydantic >=1.1
    - requests >=2.7

test:
  imports:
    - pandasdmx
    - pandasdmx.reader.sdmxml
    - pandasdmx.writer

about:
  home: https://github.com/dr-leo/pandasdmx
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Statistical Data and Metadata eXchange (SDMX) for the Python data ecosystem
  doc_url: https://pandasdmx.readthedocs.io/
  dev_url: https://github.com/dr-leo/pandasdmx

extra:
  recipe-maintainers:
    - dr-leo
